#!/usr/bin/env python3
"""Write executable, label-blind A0 trigger specifications for the 41-case set."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from trigger_analytic_taxonomy import classification_for, validate_case_inventory  # noqa: E402


def leaf(field: str, op: str, value: Any) -> dict[str, Any]:
    return {"field": field, "op": op, "value": value}


def all_of(*items: dict[str, Any]) -> dict[str, Any]:
    return {"all": list(items)}


def any_of(*items: dict[str, Any]) -> dict[str, Any]:
    return {"any": list(items)}


EID = lambda value: leaf("event_code", "eq", value)
ATTR = lambda name, op, value: leaf(f"attributes.{name}", op, value)


RULES: dict[str, dict[str, Any]] = {
    "ACCT-001": {
        "title": "Local account creation command",
        "predicate": all_of(EID(1), ATTR("command_line", "regex", r"(?i)\bnet(?:\.exe)?\s+user\s+(?:/add\s+\S+|\S+\s+\S+\s+/add)")),
        "rationale": "A process command line requesting local account creation is a reproducible account-persistence alert surface.",
    },
    "AMQ-001": {
        "title": "Java-spawned command stages and starts a downloaded file",
        "predicate": all_of(
            EID(1),
            ATTR("image", "iendswith", r"\cmd.exe"),
            ATTR("parent_image", "iendswith", r"\java.exe"),
            ATTR("command_line", "icontains", "certutil"),
            ATTR("command_line", "regex", r"(?i)https?://"),
            ATTR("command_line", "regex", r"(?i)\bstart\s+/B\b"),
        ),
        "rationale": "A Java child shell that retrieves a file and starts it in the background is a plausible exploitation alert independent of outcome labels.",
    },
    "BF-001": {
        "title": "Burst of inbound RDP connections from one source",
        "predicate": all_of(EID(3), ATTR("destination_port", "eq", "3389"), ATTR("initiated", "ieq", "false")),
        "aggregation": {
            "group_by": ["attributes.source_ip", "attributes.destination_ip", "attributes.destination_port"],
            "count_gte": 10,
            "within_seconds_lte": 600,
            "distinct": {"field": "attributes.source_port", "count_gte": 10},
        },
        "selection": "earliest_in_highest_count_group",
        "rationale": "The alert is generated by an inbound RDP burst, not by a hand-picked individual network event; A0 is the earliest representative event in the largest qualifying group.",
    },
    "BF-002": {
        "title": "Rapid failed-logon spray across distinct usernames",
        "predicate": all_of(EID(4625), ATTR("sub_status", "ieq", "0xc0000064")),
        "aggregation": {
            "group_by": ["computer", "attributes.workstation_name"],
            "count_gte": 10,
            "within_seconds_lte": 60,
            "distinct": {"field": "attributes.target_user_name", "count_gte": 10},
        },
        "selection": "earliest_in_highest_count_group",
        "rationale": "A rapid burst of unknown-account failures over many target usernames is a password-spray analytic; A0 represents the qualifying group.",
    },
    "CERT-001": {
        "title": "Certificate private-key export with certutil",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\certutil.exe"), ATTR("command_line", "icontains", "-privatekey"), ATTR("command_line", "icontains", "-exportpfx")),
        "rationale": "Exporting a certificate and private key with certutil is a stable credential-material alert surface.",
    },
    "COL-001": {
        "title": "Command-line creation of a split compressed archive",
        "predicate": all_of(EID(1), ATTR("image", "regex", r"(?i)\\7z(?:a)?\.exe$"), ATTR("command_line", "regex", r"(?i)\s+a\s+"), ATTR("command_line", "regex", r"(?i)\s-v\d+"), ATTR("command_line", "icontains", ".zip")),
        "rationale": "Creation of a volume-split archive from the command line is a reproducible collection and staging alert surface.",
    },
    "CRED-001": {
        "title": "Winlogon default-user registry modification",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\reg.exe"), ATTR("command_line", "regex", r"(?i)\badd\b"), ATTR("command_line", "icontains", r"\CurrentVersion\Winlogon"), ATTR("command_line", "icontains", "DefaultUserName")),
        "rationale": "A command that writes Winlogon DefaultUserName is a reproducible credential and autologon configuration alert.",
    },
    "DISC-001": {
        "title": "Domain account enumeration with net user",
        "predicate": all_of(EID(1), ATTR("image", "regex", r"(?i)\\net(?:1)?\.exe$"), ATTR("command_line", "regex", r"(?i)\buser\b.*\s/domain\b")),
        "rationale": "Domain-wide account enumeration using the native net utility is a standard discovery alert surface.",
    },
    "DISC-002": {
        "title": "Operating-system discovery with WMIC",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\wmic.exe"), ATTR("command_line", "regex", r"(?i)\bOS\s+get\s+Version\b")),
        "rationale": "WMIC querying the operating-system version is a behavioural system-discovery rule; its parent context is not used to force the trigger.",
        "scope_filter": leaf("computer", "ieq", "ar-win-2.attackrange.local"),
        "scope_description": "All events for the pre-declared ar-win-2 asset in the multi-host source log.",
        "selection": "latest_match",
        "selection_justification": "The source contains periodic inventory cycles; the latest matching version query anchors the final complete cycle retained by the case.",
    },
    "DISC-003": {
        "title": "Local-account enumeration with PowerShell",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\powershell.exe"), ATTR("command_line", "regex", r"(?i)\bGet-LocalUser\b")),
        "rationale": "PowerShell invocation of Get-LocalUser is a direct local-account discovery alert surface.",
    },
    "DISC-004": {
        "title": "Installed-software version query through the registry",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\reg.exe"), ATTR("command_line", "regex", r"(?i)\bquery\b"), ATTR("command_line", "icontains", r"Internet Explorer"), ATTR("command_line", "icontains", "svcVersion")),
        "rationale": "Querying a product version from the registry is a reproducible software-discovery alert surface.",
    },
    "EVL-001": {
        "title": "Windows Event Log service disabled in the registry",
        "predicate": all_of(EID(13), ATTR("target_object", "iendswith", r"\Services\EventLog\Start"), ATTR("details", "regex", r"(?i)(0x0*4|DWORD.*4)")),
        "rationale": "Setting the EventLog service Start value to disabled is a direct defence-evasion alert surface.",
    },
    "FW-001": {
        "title": "Inbound Windows Firewall allow rule creation",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\netsh.exe"), ATTR("command_line", "regex", r"(?i)advfirewall\s+firewall\s+add\s+rule"), ATTR("command_line", "regex", r"(?i)action\s*=\s*allow")),
        "rationale": "Creating an inbound allow rule with netsh is a stable firewall-modification alert surface.",
    },
    "GPO-001": {
        "title": "Remote access to Group Policy objects in SYSVOL",
        "predicate": all_of(EID(5145), ATTR("share_name", "iendswith", r"\SYSVOL"), ATTR("relative_target", "regex", r"(?i)(^|\\)Policies$"), ATTR("access_mask", "ieq", "0x100081")),
        "rationale": "Access to the Policies tree over SYSVOL is a reproducible GPO-access alert surface; routine context is assessed after triggering.",
    },
    "ING-001": {
        "title": "External DLL retrieval with curl",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\curl.exe"), ATTR("command_line", "regex", r"(?i)https?://"), ATTR("command_line", "regex", r"(?i)(?:-o|--output)\s+\S+\.dll\b")),
        "rationale": "A native curl process retrieving a DLL to disk is a reproducible ingress-transfer alert surface.",
    },
    "ING-002": {
        "title": "Remote transfer job launched with bitsadmin",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\bitsadmin.exe"), ATTR("command_line", "regex", r"(?i)\s/transfer\s"), ATTR("command_line", "regex", r"(?i)https?://")),
        "rationale": "Starting a BITS transfer from an external URL is a behavioural ingress-transfer alert independent of transfer completion.",
    },
    "INJ-001": {
        "title": "Remote thread creation with an unbacked start address",
        "predicate": all_of(EID(8), ATTR("start_module", "eq", "-")),
        "rationale": "A Sysmon remote-thread event whose start address is not mapped to a module is a process-injection analytic.",
    },
    "LGN-002": {
        "title": "UserInitMprLogonScript registry persistence",
        "predicate": all_of(EID(13), ATTR("target_object", "iendswith", r"\Environment\UserInitMprLogonScript"), ATTR("registry_event", "ieq", "SetValue")),
        "rationale": "Setting UserInitMprLogonScript is a stable logon-persistence alert surface, regardless of later execution.",
    },
    "LOGON-001": {
        "title": "UserInitMprLogonScript registry persistence",
        "predicate": all_of(EID(13), ATTR("target_object", "iendswith", r"\Environment\UserInitMprLogonScript"), ATTR("registry_event", "ieq", "SetValue")),
        "rationale": "Setting UserInitMprLogonScript is a stable logon-persistence alert surface, regardless of later execution.",
        "selection": "latest_match",
        "selection_justification": "The case evaluates the final configuration lifecycle, so the latest matching SetValue is the deterministic alert anchor.",
    },
    "LS-001": {
        "title": "High-access process handle opened to LSASS",
        "rationale": "A known dump-capable process opening a high-access handle to LSASS is a direct credential-access analytic.",
        "predicate": all_of(EID(10), ATTR("target_image", "iendswith", r"\lsass.exe"), ATTR("source_image", "iendswith", r"\mimikatz.exe"), ATTR("granted_access", "ieq", "0x1010")),
        "selection": "latest_match",
        "selection_justification": "Two equivalent Mimikatz accesses form one sub-second burst; the latest matching row is the declared deterministic representative.",
    },
    "LS-002": {
        "title": "Process dump utility invoked with an LSASS-suggesting target",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\createdump.exe"), ATTR("command_line", "regex", r"(?i)\.dmp\b"), ATTR("command_line", "icontains", "lsass")),
        "rationale": "A dump utility invoked with an LSASS-named output is a stable credential-access alert surface without asserting dump success.",
    },
    "LS-003": {
        "title": "Task Manager obtains full access to LSASS",
        "predicate": all_of(EID(10), ATTR("source_image", "iendswith", r"\taskmgr.exe"), ATTR("target_image", "iendswith", r"\lsass.exe"), ATTR("granted_access", "ieq", "0x1fffff"), ATTR("call_trace", "icontains", "dbgcore.dll")),
        "rationale": "Task Manager opening LSASS with full access is a reproducible high-risk credential-access alert surface.",
    },
    "OD-001": {
        "title": "Volume shadow copies deletion command",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\vssadmin.exe"), ATTR("command_line", "regex", r"(?i)\bdelete\s+shadows\b"), ATTR("command_line", "icontains", "/all")),
        "rationale": "A command requesting deletion of all volume shadow copies is a stable destructive-impact alert surface.",
    },
    "PS-001": {
        "title": "Encoded PowerShell with execution-policy override",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\powershell.exe"), ATTR("parent_image", "iendswith", r"\powershell.exe"), ATTR("command_line", "regex", r"(?i)-(?:e|enc|encodedcommand)\s+[A-Za-z0-9+/=]{20,}"), ATTR("command_line", "regex", r"(?i)-ExecutionPolicy\s+(?:Bypass|Unrestricted)"), leaf("derived.decoded_command", "icontains", "$input | Out-String")),
        "rationale": "Encoded PowerShell combined with an execution-policy override is a reproducible suspicious scripting alert.",
    },
    "PS-002": {
        "title": "Hidden PowerShell download through WebClient",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\powershell.exe"), ATTR("command_line", "regex", r"(?i)-WindowStyle\s+hidden"), ATTR("command_line", "icontains", "Net.WebClient"), ATTR("command_line", "icontains", "DownloadFile")),
        "rationale": "Hidden PowerShell using WebClient.DownloadFile is a stable ingress and script-execution alert surface.",
    },
    "PS-003": {
        "title": "String-obfuscated PowerShell piped to Invoke-Expression",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\powershell.exe"), ATTR("command_line", "regex", r"(?i)\.replace\s*\("), ATTR("command_line", "regex", r"(?i)\|\s*(?:iex|invoke-expression)\b")),
        "rationale": "String replacement followed by Invoke-Expression is a reproducible obfuscated-PowerShell analytic; decoded intent is evaluated later.",
    },
    "PS-004": {
        "title": "PowerShell loads the SharpHound collection module",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\powershell.exe"), ATTR("command_line", "regex", r"(?i)\bImport-Module\b"), ATTR("command_line", "icontains", "SharpHound.ps1")),
        "rationale": "Loading a SharpHound module through PowerShell is a direct directory-collection alert surface.",
    },
    "RDL-001": {
        "title": "WebDAV DavSetCookie execution through rundll32",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\rundll32.exe"), ATTR("command_line", "regex", r"(?i)davclnt\.dll,?DavSetCookie")),
        "rationale": "Rundll32 invoking the WebDAV DavSetCookie export is a reproducible LOLBin alert; benign WebClient context is considered after triggering.",
    },
    "RK-001": {
        "title": "Run-key registry value creation",
        "predicate": all_of(EID(13), ATTR("target_object", "regex", r"(?i)\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\[^\\]+$"), ATTR("registry_event", "ieq", "SetValue")),
        "rationale": "Creating a value beneath a user Run key is a stable registry-persistence alert surface.",
    },
    "RTLO-001": {
        "title": "Executable filename contains a right-to-left override",
        "predicate": all_of(EID(1), ATTR("image", "contains", "\u202e")),
        "rationale": "A process image containing the Unicode right-to-left override character is a reproducible masquerading analytic.",
    },
    "RUN-001": {
        "title": "Rundll32 loads a DLL-like file from user AppData",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\rundll32.exe"), ATTR("command_line", "icontains", "\\AppData\\"), ATTR("command_line", "regex", r"(?i)\.(?:dll|lock),[A-Za-z0-9_]+")),
        "rationale": "Rundll32 loading an export from a user-writable AppData path is a stable proxy-execution alert surface.",
    },
    "SMB-001": {
        "title": "WMI-spawned shell redirects output to ADMIN share",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\cmd.exe"), ATTR("parent_image", "iendswith", r"\WmiPrvSE.exe"), ATTR("command_line", "regex", r"(?i)\\\\127\.0\.0\.1\\ADMIN\$"), {"not": ATTR("command_line", "regex", r"(?i)/c\s+cd(?:\s|$)")}),
        "rationale": "A WMI provider spawning a shell that redirects command output through ADMIN$ is a reproducible remote-execution pattern.",
    },
    "SMB-002": {
        "title": "SMB access to the LSARPC named pipe",
        "predicate": all_of(EID(5145), ATTR("share_name", "iendswith", r"\IPC$"), ATTR("relative_target", "ieq", "lsarpc")),
        "rationale": "Access to the LSARPC named pipe over IPC$ is a reproducible directory-enumeration alert surface; routine machine context is evaluated separately.",
    },
    "ST-001": {
        "title": "Scheduled task created for startup or logon execution",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\schtasks.exe"), ATTR("command_line", "regex", r"(?i)\s/create\s"), ATTR("command_line", "regex", r"(?i)\s/sc\s+onstart\b"), ATTR("command_line", "regex", r"(?i)\s/ru\s+system\b")),
        "rationale": "Creation of an on-start or on-logon task is a reproducible scheduled-persistence alert surface.",
    },
    "ST-002": {
        "title": "Scheduled task action references an alternate data stream",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\schtasks.exe"), ATTR("command_line", "regex", r"(?i)\s/Create\s"), ATTR("command_line", "regex", r"(?i)\s/TR\s"), ATTR("command_line", "regex", r"(?i)[A-Z]:\\[^\"\r\n]+:[^\"\s]+")),
        "rationale": "A scheduled-task action that invokes content from an NTFS alternate data stream is a stable persistence alert surface.",
    },
    "ST-003": {
        "title": "Scheduled task created to run a program as SYSTEM",
        "predicate": all_of(EID(4698), ATTR("run_as", "icontains", "SYSTEM"), any_of(ATTR("action_command", "iendswith", ".bat"), ATTR("action_command", "iendswith", ".cmd"), ATTR("action_command", "iendswith", ".exe"))),
        "rationale": "A newly registered task executing a program or script as SYSTEM is a plausible scheduled-task alert surface; provenance is contextual evidence.",
        "scope_filter": leaf("computer", "ieq", "win-host-mhaag-attack-range-569"),
        "scope_description": "All events for the pre-declared endpoint asset in the multi-host Security log.",
    },
    "SVC-001": {
        "title": "Service binary path changed to a command interpreter",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\sc.exe"), ATTR("command_line", "regex", r"(?i)\bconfig\b"), ATTR("command_line", "regex", r"(?i)binpath\s*="), any_of(ATTR("command_line", "icontains", "powershell"), ATTR("command_line", "icontains", "cmd.exe"))),
        "rationale": "Changing a service binary path to a command interpreter is a reproducible service-persistence alert surface.",
    },
    "UAC-001": {
        "title": "High-integrity sdclt process launched from a shell",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\sdclt.exe"), ATTR("integrity_level", "ieq", "High"), ATTR("parent_image", "regex", r"(?i)\\(cmd|powershell)\.exe$")),
        "rationale": "A high-integrity sdclt process launched from a command shell is a reproducible UAC-bypass alert surface.",
    },
    "UQP-001": {
        "title": "Service created with an unquoted Program Files binary path",
        "predicate": all_of(EID(1), ATTR("image", "iendswith", r"\sc.exe"), ATTR("command_line", "regex", r"(?i)\bcreate\b"), ATTR("command_line", "regex", r"(?i)binpath\s*=\s*\"?[A-Z]:\\Program Files\\[^\"]+\.exe")),
        "rationale": "Creating a service with an unquoted executable path containing spaces is a reproducible service-path hijack alert surface.",
    },
    "WMI-001": {
        "title": "WMI command-line consumer contains hidden encoded PowerShell",
        "predicate": all_of(EID(20), ATTR("destination", "icontains", "powershell"), ATTR("destination", "regex", r"(?i)-(?:e|enc|encodedcommand)\s+[A-Za-z0-9+/=]{20,}"), ATTR("destination", "regex", r"(?i)-(?:w|windowstyle)\s+hidden")),
        "rationale": "A WMI command-line consumer embedding hidden encoded PowerShell is a direct persistence-mechanism alert surface.",
    },
    "WMI-002": {
        "title": "WMI command-line consumer contains hidden encoded PowerShell",
        "predicate": all_of(EID(20), ATTR("destination", "icontains", "powershell"), ATTR("destination", "regex", r"(?i)-(?:e|enc|encodedcommand)\s+[A-Za-z0-9+/=]{20,}"), ATTR("destination", "regex", r"(?i)-(?:w|windowstyle)\s+hidden")),
        "rationale": "A WMI command-line consumer embedding hidden encoded PowerShell is a direct persistence-mechanism alert surface.",
    },
}


def case_dirs() -> dict[str, Path]:
    result: dict[str, Path] = {}
    for path in ROOT.glob("tier*/*/*/*/build/case.json"):
        config = json.loads(path.read_text(encoding="utf-8"))
        result[config["case_id"]] = path.parent.parent
    return result


def main() -> None:
    directories = case_dirs()
    missing = sorted(set(directories) - set(RULES))
    extra = sorted(set(RULES) - set(directories))
    if missing or extra:
        raise SystemExit(f"rule inventory mismatch: missing={missing}, extra={extra}")
    validate_case_inventory(directories)

    for case_id, case_dir in sorted(directories.items()):
        config = json.loads((case_dir / "build/case.json").read_text(encoding="utf-8"))
        rule = RULES[case_id]
        classification = classification_for(case_id)
        configured_scope = bool(config.get("computer")) or any(
            source.get("computer") for source in config.get("sources", [])
        )
        explicit_scope = rule.get("scope_filter")
        spec = {
            "schema_version": "1.0",
            "case_id": case_id,
            "rule_id": f"SAFESOC-TRG-{case_id}",
            **classification,
            "title": rule["title"],
            "formalisation_timing": "retrospective_pre_extension_audit",
            "rule_origin": {
                "type": "project_analytic",
                "reference": "queries/retrieval_spec.md (Q1/main-alert analytic); executable form formalised under alert-anchor policy v1.0",
            },
            "scope": {
                "basis": "declared_asset_scope" if configured_scope or explicit_scope else "full_source",
                "complete_legal_scope": True,
                "description": rule.get(
                    "scope_description",
                    "All events in the configured raw source after any pre-existing host and sensor scope is applied."
                    if configured_scope
                    else "All events in the configured raw source; no event-level answer selector is applied.",
                ),
            },
            "event_predicate": rule["predicate"],
            "selection": {"strategy": rule.get("selection", "earliest_match")},
            "expected_a0": {"record_key": str(config["selection"]["A0"])},
            "rationale": rule["rationale"],
        }
        if explicit_scope:
            spec["scope"]["filter_predicate"] = explicit_scope
        if rule.get("selection_justification"):
            spec["selection"]["justification"] = rule["selection_justification"]
        if "aggregation" in rule:
            spec["aggregation"] = rule["aggregation"]
        target = case_dir / "annotations/trigger_spec.json"
        target.write_text(json.dumps(spec, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
